---
#  add Java Environment Variables /etc/profile
- name: Variables Java al /etc/profile
  become: yes
  shell:  "{{ item }}"
  with_items:
    - echo export JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto >> /etc/profile
    - echo export PATH=$JAVA_HOME/bin:$PATH >> /etc/profile

    
