---
# Copy ZIP WSO2 
- name: Copy product  
  become: yes
  copy:
    src: WSO2.zip
    dest: /tmp/
    mode: 0777

# Unzip
- name: unzips
  become: yes
  ansible.builtin.unarchive:
    src: "/tmp/WSO2.zip"
    dest: "/opt/"

# Rename wso2
- name: renombrar wso2 en opt
  become: yes
  shell: mv /opt/wso2am-4.1.0 /opt/wso2

# Delete ZIP and temp folder
- name: remove product.zip
  become: yes
  file:
    path: "/tmp/WSO2.zip"
    state: absent