---
# Download Java Amazon Corretto
 - name: Download java java-temp
   ansible.builtin.get_url:
     url: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.rpm 
     dest: /tmp
     mode: 0777
   environment: 
     https_proxy: http://proxy-ha.client.com:80

- name: copy java - java-temp
  copy:
    src: JDK11.rpm 
    dest: /tmp
    mode: 0777

# Install Java Amazon Corretto RPM
- name: Instalar java correto
  become: yes
  yum: 
    name: /tmp/JDK11.rpm
    state: present 
   
# Delete RPM 
- name: remove corretto-temp
  become: yes
  file:
    path: /tmp/JDK11.rpm
    state: absent
