---
# Copy Filebeat 
- name: Download filebeat - filebeat-temp
  copy:
    src: filebeat-8.2.3-x86_64.rpm
    dest: /tmp
    mode: 0777

# install Filebeat
- name: Install filebeat
  become: yes
  yum: 
    name: /tmp/filebeat-8.2.3-x86_64.rpm
    state: present 
   
# Delete RPM temp
- name: remove filebeat-temp
  become: yes
  file:
    path: /tmp/filebeat-8.2.3-x86_64.rpm
    state: absent
