---
 - name: Installation wso2
   import_tasks: inst-wso2-product.yml

 - name: Installation java
   import_tasks: inst-wso2-java.yml
 
 - name: config java vars
   import_tasks: conf-wso2-java.yml

 - name: role preset
   import_tasks: conf-wso2-roles.yml

 - name: Installation filebeat
   import_tasks: inst-wso2-logs-filebeat.yml
   
 - name: Configuration filebeat
   import_tasks: conf-wso2-filebeat.yml
  
 - name: Copy services
   import_tasks: conf-wso2-services.yml

- name: Copy keystores
  import_tasks: conf-wso2-certs-client.yml
  
 - name: Installation conector mssql 
   import_tasks: inst-wso2-db-mssql.yml