---

# Handlers Restart services y wait

# Restart wso2
- name: restart_wso2
  become: yes
  service: 
    name: wso2.service
    state: restarted
    enabled: yes
  listen: "restart_apimtm"

- name: restart_wso2
  become: yes
  service: 
    name: wso2.service
    state: restarted
    enabled: yes
  listen: "restart_apimcp"

- name: restart_wso2
  become: yes
  service: 
    name: wso2.service
    state: restarted
    enabled: yes
  listen: "restart_apimgw"

# Handler wait port 9711 Traffic Manager
- name: wait_TM 9711
  wait_for:
    port: 9711
    timeout: 300
  listen: "restart_apimtm"

# Handler wait port 9443 Control Plane
- name: wait_CP 9443
  wait_for:
    port: 9443
    timeout: 300
  listen: "restart_apimcp"