### Este archivo es la configuración del Gateway de WSO2 ###
#
[server] 
hostname = "apigw.client.com"  # Agrupacion de nodos de gateway
node_ip = "127.0.0.150" 
server_role = "gateway-worker"      # Rol del nodo (define la funcion del servicio)

[user_store] 
type = "database_unique_id" 

[super_admin]                       # Se define la cuenta de superadmin (se guarda en la base de datos $shared), misma configuracion en todos los nodos para que funcione correctamente
username = "client-user"
password = "client-password"
create_admin_account = true

[database.shared_db]                # Definicion de la conexion a la base de datos $shared que será utilizada por todo el cluster WSO2
type = "mssql"
url = "jdbc:sqlserver://client.client.com:9999;databaseName=WSO2SHARED_DB;encrypt=true;TrustServerCertificate=True;SendStringParametersAsUnicode=false"
username = "USR_DB_WSO2SHARED"
password = "PASS_DB_WSO2SHARED"

[keystore.tls]                      # Definicion del archivo JKS en el que se encuentran los keypairs y certificados publicos
file_name =  "client-primary-keystore.jks"
type =  "JKS"
password =  "passwd"
alias =  "client"                 # Alias del keypair que se va a utilizar en la consola web
key_password =  "passwd"

[truststore]                        # Definicion del archivo JKS para los CA y claves publicas de los servicios externos
file_name = "client-truststore.jks"
type = "JKS"
password = "passwd"
alias =  "client"                 # Clave publica especifica para establecer comunicacion segura dentro del cluster
key_password =  "passwd"

[transport.https]                   # Validamos los puertos que se estaran utilizando
properties.port = 9443              # Puerto de salida
properties.proxyPort = 443          # Puerto haproxy

[apim.key_manager]                  # Indicamos key manager local (embeded) en los control planes
service_url = "https://apim.client.com/services/"

[apim.sync_runtime_artifacts.gateway] 
gateway_labels =["Default"]

[apim.event_hub]                    # Configuracion del endpoint de eventos
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://apim.client.com/services/"
event_listening_endpoints = ["tcp://clientapimcp01.client.com:5672", "tcp://clientapimcp02.client.com:5672"]

[apim.throttling]                   # Seteo de los Traffic manager
username= "admin"
password= "admin"
throttle_decision_endpoints = ["tcp://clientapimtm01.client.com:5672", "tcp://clientapimtm02.client.com:5672"]
enable_unlimited_tier = true
enable_header_based_throttling = false
enable_jwt_claim_based_throttling = false
enable_query_param_based_throttling = false

[[apim.throttling.url_group]]       # Puertos de TM 1
traffic_manager_urls=["tcp://clientapimtm01.client.com:9611"]
traffic_manager_auth_urls=["ssl://clientapimtm01.client.com:9711"]

[[apim.throttling.url_group]]       # Puertos de TM 2
traffic_manager_urls=["tcp://clientapimtm02.client.com:9611"]
traffic_manager_auth_urls=["ssl://clientapimtm02.client.com:9711"]

[apim.analytics]                    # Desactivamos Analytics
enable = false
type = "elk"

 [apimgt.mutual_ssl]
 certificate_header = "sec-header"
 # This property needs to be true if the MutualSSL connection is established between the load balancer and the Gateway.
 enable_client_validation = false
 #This property needs to be true if the certificate should be decoded when it is passed from the load balancer to the Gateway.
 client_certificate_encode = false