---
- name: Configurations wso2 
  become: yes
  copy:
      src: "{{ tomlfile }}"
      dest: /opt/wso2/repository/conf/deployment.toml
      owner: root
      group: root
      mode: 0600
  # notify: "restart_{{ group_names }}"


- name: Configurations wso2 logs
  become: yes
  copy:
      src: "{{ log4j2 }}"
      dest: /opt/wso2/repository/conf/log4j2.properties
      owner: root
      group: root
      mode: 0600
  # notify: "restart_{{ group_names }}"