---
# task restart and wait 

# Restart Filebeat service
- name: restart filebeat
  become: yes
  service: 
    name: filebeat.service
    state: stopped
    enabled: yes
  listen: "restartfilebeat"

# Restart WSO2 service
- name: restart_wso2
  become: yes
  service: 
    name: wso2.service
    state: stopped
    enabled: yes
  listen: "restart"

# wait port 9711 Traffic Manager
- name: esperar_TM 9711
  wait_for:
    port: 9711
    timeout: 180
  when: '"tm" in ansible_hostname'
  listen: "restart"

# wait port 9443 Control Plane
- name: esperar_CP 9443
  wait_for:
    port: 9443
    timeout: 180
  when: '"cp" in ansible_hostname'
  listen: "restart"